### ISSUE TITLE
Can't Export File to PDF

### ISSUE THREAD

**Issue by sotch-pr35mac** [steventhanna/proton#29]
On Linux 64-bit, I can't export a file to PDF. I get two error messages that are as follows after trying to save the exported file. 

![error1](https://cloud.githubusercontent.com/assets/441131/12584449/97ba55e2-c415-11e5-833f-a2dde95b0e0d.png)

![error2](https://cloud.githubusercontent.com/assets/441131/12584450/9c148568-c415-11e5-9df6-491b64408642.png)

**Comment by steventhanna** [comment]
Things to research
- [EPIPE Conversion](https://github.com/marcbachmann/node-html-pdf/issues/35)

**Comment by steventhanna** [comment]
This issue references the old version of Proton. Reopen if still an issue.
