### ISSUE TITLE
Proton-Windows Fails to Start

### ISSUE THREAD

**Issue by optimax** [steventhanna/proton#31]
> The program can't start because node.dll is missing from your computer. Try reinstalling the program to fix this problem.

So there is more to it than just moving proton.exe to a directory of my choice...

Just sayin'...

**Comment by steventhanna** [comment]
Do you have node.js installed?

**Comment by optimax** [comment]
Yes, of course. Duh! :-) For some reason, it could not find the dll even though it was in the path. I could start it after manually copying the dll into the folder. However, there are bigger problems... I'll open another issue when I get around to it.
