### ISSUE TITLE
Export to PDF fails on OSX

### ISSUE THREAD

**Issue by candlerb** [steventhanna/proton#34]
(seems to be different issue to #29)

Running under OSX 10.9.5. If I select "Export to PDF" then nothing happens, except:

* the preview pane scrolls slightly
* 2 seconds later, the preview pane scrolls back to where it was

Nothing else - in particular, I was expecting a dialog box to open asking for a save destination.

Proton itself doesn't seem to show any version number (`About Proton` redirects to the website), but this is the file I downloaded:

~~~
$ ls -lrt ~/Downloads/Proton-OSX.zip
-rw-r--r--@ 1 brian  staff  82119959 21 Jul 20:32 /Users/brian/Downloads/Proton-OSX.zip
~~~

**Comment by steventhanna** [comment]
Thanks for letting me know, I'm actually in the process of rebasing the entire app, so adding the won't fix and keeping the issue open. If it is not a problem after the next version, this issue should be closed.

**Comment by steventhanna** [comment]
Closing this unless another problem is reported.
