### ISSUE TITLE
The font size should be flexible

### ISSUE THREAD

**Issue by JeffreySarnoff** [steventhanna/proton#38]
You have done a nice job with proton.  On a high resolution monitor the text becomes too small to read.
A menu item that allows font resizing would be of real help.  A less pressing readability enhancement would be allowing the font face to be set by the user.

**Comment by steventhanna** [comment]
I've experienced the same issue, I'll look into it and come up with a solution. Thanks

**Comment by steventhanna** [comment]
@JeffreySarnoff check out the latest release, it should have fixed your problems.

**Comment by steventhanna** [comment]
Closed with release v0.2.1
